workflow:
    rules:
        - if: '$CI_COMMIT_BRANCH && $CI_PIPELINE_SOURCE == "push" && $CI_OPEN_MERGE_REQUESTS'
          when: never
        - when: always

include:
    - local: ".gitlab/pr.yml"
    - local: ".gitlab/build.yml"
